 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examseatallotment;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Priyam Kumar
 */
public class AddClass extends javax.swing.JFrame {

    /**
     * Creates new form AddClass
     */
    public DefaultTableModel classRoom;
    AddRoom room;
    public AddClass(AddRoom room) {
        initComponents();
     this.room=room;
        classRoom=(DefaultTableModel) ClassTable.getModel();
         DBConnection connect=new DBConnection();
        connect.classResult(classRoom);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        branchName = new javax.swing.JTextField();
        semester = new javax.swing.JTextField();
        strenth = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        addClassButton = new javax.swing.JButton();
        editClassbutton = new javax.swing.JButton();
        deleteClassButton = new javax.swing.JButton();
        Arrange = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ClassTable = new javax.swing.JTable();
        addExcelFile = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 153), 3, true), "Class Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Garamond", 1, 48), new java.awt.Color(255, 102, 102))); // NOI18N

        strenth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strenthActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        jLabel2.setText("Branch name");

        jLabel3.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        jLabel3.setText("Semester");

        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        jLabel1.setText("Strength");

        addClassButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        addClassButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examseatallotment/add.png"))); // NOI18N
        addClassButton.setText("Add class");
        addClassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClassButtonActionPerformed(evt);
            }
        });

        editClassbutton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        editClassbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examseatallotment/edit-validated-icon.png"))); // NOI18N
        editClassbutton.setText("Edit");
        editClassbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editClassbuttonActionPerformed(evt);
            }
        });

        deleteClassButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        deleteClassButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examseatallotment/Delete-icon.png"))); // NOI18N
        deleteClassButton.setText("Delete");
        deleteClassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteClassButtonActionPerformed(evt);
            }
        });

        Arrange.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        Arrange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examseatallotment/Chair-icon.png"))); // NOI18N
        Arrange.setText("Arrange");
        Arrange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArrangeActionPerformed(evt);
            }
        });

        ClassTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.No", "Branch_Name", "Semester", "Strength", "Excel File"
            }
        ));
        ClassTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClassTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ClassTable);

        addExcelFile.setText("Add Excel File");
        addExcelFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addExcelFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addClassButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addComponent(editClassbutton)
                        .addGap(40, 40, 40)
                        .addComponent(deleteClassButton)
                        .addGap(46, 46, 46)
                        .addComponent(addExcelFile)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(branchName, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(semester, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(strenth, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(264, 264, 264))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(168, 168, 168))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(Arrange)
                        .addGap(368, 368, 368))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(branchName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(semester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(strenth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addClassButton)
                    .addComponent(editClassbutton)
                    .addComponent(deleteClassButton)
                    .addComponent(addExcelFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(Arrange)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void strenthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strenthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_strenthActionPerformed

    private void addClassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClassButtonActionPerformed
        // TODO add your handling code here:
          classRoom.insertRow(classRoom.getRowCount(), new Object[]{classRoom.getRowCount()+1,branchName.getText(),semester.getText(),strenth.getText(),0});
     
    }//GEN-LAST:event_addClassButtonActionPerformed

    private void editClassbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editClassbuttonActionPerformed
        
         classRoom.setValueAt(branchName.getText(), ClassTable.getSelectedRow(), 1);
       classRoom.setValueAt(semester.getText(), ClassTable.getSelectedRow(), 2);
       classRoom.setValueAt( strenth.getText(), ClassTable.getSelectedRow(), 3);
      // classRoom.setValueAt( startrollno.getText(), ClassTable.getSelectedRow(), 4);
        
    }//GEN-LAST:event_editClassbuttonActionPerformed

    private void deleteClassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteClassButtonActionPerformed
        // TODO add your handling code here:
         classRoom.removeRow(ClassTable.getSelectedRow());
        for(int i=0;i<classRoom.getRowCount();i++)
            classRoom.setValueAt(i+1, i, 0);
    }//GEN-LAST:event_deleteClassButtonActionPerformed

    private void ClassTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClassTableMouseClicked
        // TODO add your handling code here:
          branchName.setText(String.valueOf(classRoom.getValueAt(ClassTable.getSelectedRow(), 1)));
         semester.setText(String.valueOf(classRoom.getValueAt(ClassTable.getSelectedRow(), 2)));
         strenth.setText(String.valueOf(classRoom.getValueAt(ClassTable.getSelectedRow(), 3)));
        // startrollno.setText(String.valueOf(classRoom.getValueAt(ClassTable.getSelectedRow(), 4)));
    }//GEN-LAST:event_ClassTableMouseClicked

    private void ArrangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArrangeActionPerformed
        // TODO add your handling code here:
        //AddRoom room=new AddRoom();
       
      //  classRoom.insertRow(classRoom.getRowCount(), new Object[]{classRoom.getRowCount()+1,String.valueOf( room.modelRoom.getValueAt(1, 1)),String.valueOf( room.modelRoom.getValueAt(1, 2)),String.valueOf( room.modelRoom.getValueAt(1, 3)),startrollno.getText()});
          //room.setVisible(true);
            String branchname;
        int semester;
        int strength;
        int xlfile;
          DBConnection connect=new DBConnection();
          connect.deleteClassQuery();
           for(int i=0;i<classRoom.getRowCount();i++)
           {branchname=String.valueOf(classRoom.getValueAt(i, 1));
           semester=Integer.parseInt(String.valueOf(classRoom.getValueAt(i, 2)));
           strength=Integer.parseInt(String.valueOf(classRoom.getValueAt(i, 3)));
             xlfile=Integer.parseInt(String.valueOf(classRoom.getValueAt(i, 4))); 
              connect.theQuery("insert into classes (branch_name,semester,strength,xlfile) values('"+branchname+"',"+semester+","+strength+","+xlfile+")");
           
           }
          this.setVisible(false);
          Arrangement ar=new Arrangement(this,room);
          ar.setTitle("Automatic Seating Arrangement");
          
         // ar.setVisible(true);
    }//GEN-LAST:event_ArrangeActionPerformed

    private void addExcelFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addExcelFileActionPerformed
        // TODO add your handling code here:
        FileChooserTest f=new FileChooserTest();
      if(f.run(String.valueOf(classRoom.getValueAt(ClassTable.getSelectedRow(), 1)), String.valueOf(classRoom.getValueAt(ClassTable.getSelectedRow(), 2)))==1)
        classRoom.setValueAt( 1, ClassTable.getSelectedRow(), 4);
    }//GEN-LAST:event_addExcelFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new AddClass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Arrange;
    public javax.swing.JTable ClassTable;
    private javax.swing.JButton addClassButton;
    private javax.swing.JButton addExcelFile;
    private javax.swing.JTextField branchName;
    private javax.swing.JButton deleteClassButton;
    private javax.swing.JButton editClassbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField semester;
    private javax.swing.JTextField strenth;
    // End of variables declaration//GEN-END:variables
}
